language: java
sudo: false
jdk:
  - oraclejdk8
services:
  - mysql
  - postgresql
script: mvn clean test
after_success:
  - mvn clean site -Dcobertura.report.format=xml
  - bash <(curl -s https://codecov.io/bash)

