language: java
sudo: false
jdk:
  - oraclejdk8
addons:
    postgresql: 9.3
    apt:
        packages:
        - postgresql-9.3-postgis-2.1
services:
  - mysql
  - postgresql
before_script:
  - psql -U postgres -c "create extension postgis"
script: mvn clean test
after_success:
  - mvn clean site -Dcobertura.report.format=xml
  - bash <(curl -s https://codecov.io/bash)
