language: java
dist: trusty
sudo: false
jdk:
  - oraclejdk8
addons:
    postgresql: 9.3
    apt:
        packages:
        - postgresql-9.3-postgis-2.3
services:
  - mysql
  - postgresql
before_install:
  - mysql -e "CREATE DATABASE vagrant;"
before_script:
  - psql -U postgres -c "create extension postgis"
script: mvn clean test
after_success:
  - mvn clean site -Dcobertura.report.format=xml
  - bash <(curl -s https://codecov.io/bash)
