language: java
sudo: false
jdk:
  - oraclejdk8
services:
  - mysql
  - postgresql
script: mvn clean cobertura:cobertura -Dcobertura.report.format=xml
after_success:
  - bash <(curl -s https://codecov.io/bash)

