language: java
sudo: false
jdk:
  - oraclejdk8
services:
  - mysql
  - postgresql
script: mvn cobertura:cobertura
install: mvn install -DskipTests -Dgpg.skip
after_success:
  - bash <(curl -s https://codecov.io/bash)

